using FunctionProxyDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace FunctionProxyDemo.Services
{
    public class DataService
    {
        static List<CountryData> countries = new List<CountryData> {
            new CountryData {Name= "Afghanistan", Code= "AF"},
            new CountryData {Name= "land Islands", Code= "AX"},
            new CountryData {Name= "Albania", Code= "AL"},
            new CountryData {Name= "Algeria", Code= "DZ"},
            new CountryData {Name= "American Samoa", Code= "AS"},
            new CountryData {Name= "AndorrA", Code= "AD"},
            new CountryData {Name= "Angola", Code= "AO"},
            new CountryData {Name= "Anguilla", Code= "AI"},
            new CountryData {Name= "Antarctica", Code= "AQ"},
            new CountryData {Name= "Antigua and Barbuda", Code= "AG"},
            new CountryData {Name= "Argentina", Code= "AR"},
            new CountryData {Name= "Armenia", Code= "AM"},
            new CountryData {Name= "Aruba", Code= "AW"},
            new CountryData {Name= "Australia", Code= "AU"},
            new CountryData {Name= "Austria", Code= "AT"},
            new CountryData {Name= "Azerbaijan", Code= "AZ"},
            new CountryData {Name= "Bahamas", Code= "BS"},
            new CountryData {Name= "Bahrain", Code= "BH"},
            new CountryData {Name= "Bangladesh", Code= "BD"},
            new CountryData {Name= "Barbados", Code= "BB"},
            new CountryData {Name= "Belarus", Code= "BY"},
            new CountryData {Name= "Belgium", Code= "BE"},
            new CountryData {Name= "Belize", Code= "BZ"},
            new CountryData {Name= "Benin", Code= "BJ"},
            new CountryData {Name= "Bermuda", Code= "BM"},
            new CountryData {Name= "Bhutan", Code= "BT"},
            new CountryData {Name= "Bolivia", Code= "BO"},
            new CountryData {Name= "Bosnia and Herzegovina", Code= "BA"},
            new CountryData {Name= "Botswana", Code= "BW"},
            new CountryData {Name= "Bouvet Island", Code= "BV"},
            new CountryData {Name= "Brazil", Code= "BR"},
            new CountryData {Name= "British Indian Ocean Territory", Code= "IO"},
            new CountryData {Name= "Brunei Darussalam", Code= "BN"},
            new CountryData {Name= "Bulgaria", Code= "BG"},
            new CountryData {Name= "Burkina Faso", Code= "BF"},
            new CountryData {Name= "Burundi", Code= "BI"},
            new CountryData {Name= "Cambodia", Code= "KH"},
            new CountryData {Name= "Cameroon", Code= "CM"},
            new CountryData {Name= "Canada", Code= "CA"},
            new CountryData {Name= "Cape Verde", Code= "CV"},
            new CountryData {Name= "Cayman Islands", Code= "KY"},
            new CountryData {Name= "Central African Republic", Code= "CF"},
            new CountryData {Name= "Chad", Code= "TD"},
            new CountryData {Name= "Chile", Code= "CL"},
            new CountryData {Name= "China", Code= "CN"},
            new CountryData {Name= "Christmas Island", Code= "CX"},
            new CountryData {Name= "Cocos (Keeling) Islands", Code= "CC"},
            new CountryData {Name= "Colombia", Code= "CO"},
            new CountryData {Name= "Comoros", Code= "KM"},
            new CountryData {Name= "Congo", Code= "CG"},
            new CountryData {Name= "Congo, The Democratic Republic of the", Code= "CD"},
            new CountryData {Name= "Cook Islands", Code= "CK"},
            new CountryData {Name= "Costa Rica", Code= "CR"},
            new CountryData {Name= "Cote D'Ivoire", Code= "CI"},
            new CountryData {Name= "Croatia", Code= "HR"},
            new CountryData {Name= "Cuba", Code= "CU"},
            new CountryData {Name= "Cyprus", Code= "CY"},
            new CountryData {Name= "Czech Republic", Code= "CZ"},
            new CountryData {Name= "Denmark", Code= "DK"},
            new CountryData {Name= "Djibouti", Code= "DJ"},
            new CountryData {Name= "Dominica", Code= "DM"},
            new CountryData {Name= "Dominican Republic", Code= "DO"},
            new CountryData {Name= "Ecuador", Code= "EC"},
            new CountryData {Name= "Egypt", Code= "EG"},
            new CountryData {Name= "El Salvador", Code= "SV"},
            new CountryData {Name= "Equatorial Guinea", Code= "GQ"},
            new CountryData {Name= "Eritrea", Code= "ER"},
            new CountryData {Name= "Estonia", Code= "EE"},
            new CountryData {Name= "Ethiopia", Code= "ET"},
            new CountryData {Name= "Falkland Islands (Malvinas)", Code= "FK"},
            new CountryData {Name= "Faroe Islands", Code= "FO"},
            new CountryData {Name= "Fiji", Code= "FJ"},
            new CountryData {Name= "Finland", Code= "FI"},
            new CountryData {Name= "France", Code= "FR"},
            new CountryData {Name= "French Guiana", Code= "GF"},
            new CountryData {Name= "French Polynesia", Code= "PF"},
            new CountryData {Name= "French Southern Territories", Code= "TF"},
            new CountryData {Name= "Gabon", Code= "GA"},
            new CountryData {Name= "Gambia", Code= "GM"},
            new CountryData {Name= "Georgia", Code= "GE"},
            new CountryData {Name= "Germany", Code= "DE"},
            new CountryData {Name= "Ghana", Code= "GH"},
            new CountryData {Name= "Gibraltar", Code= "GI"},
            new CountryData {Name= "Greece", Code= "GR"},
            new CountryData {Name= "Greenland", Code= "GL"},
            new CountryData {Name= "Grenada", Code= "GD"},
            new CountryData {Name= "Guadeloupe", Code= "GP"},
            new CountryData {Name= "Guam", Code= "GU"},
            new CountryData {Name= "Guatemala", Code= "GT"},
            new CountryData {Name= "Guernsey", Code= "GG"},
            new CountryData {Name= "Guinea", Code= "GN"},
            new CountryData {Name= "Guinea-Bissau", Code= "GW"},
            new CountryData {Name= "Guyana", Code= "GY"},
            new CountryData {Name= "Haiti", Code= "HT"},
            new CountryData {Name= "Heard Island and Mcdonald Islands", Code= "HM"},
            new CountryData {Name= "Holy See (Vatican City State)", Code= "VA"},
            new CountryData {Name= "Honduras", Code= "HN"},
            new CountryData {Name= "Hong Kong", Code= "HK"},
            new CountryData {Name= "Hungary", Code= "HU"},
            new CountryData {Name= "Iceland", Code= "IS"},
            new CountryData {Name= "India", Code= "IN"},
            new CountryData {Name= "Indonesia", Code= "ID"},
            new CountryData {Name= "Iran, Islamic Republic Of", Code= "IR"},
            new CountryData {Name= "Iraq", Code= "IQ"},
            new CountryData {Name= "Ireland", Code= "IE"},
            new CountryData {Name= "Isle of Man", Code= "IM"},
            new CountryData {Name= "Israel", Code= "IL"},
            new CountryData {Name= "Italy", Code= "IT"},
            new CountryData {Name= "Jamaica", Code= "JM"},
            new CountryData {Name= "Japan", Code= "JP"},
            new CountryData {Name= "Jersey", Code= "JE"},
            new CountryData {Name= "Jordan", Code= "JO"},
            new CountryData {Name= "Kazakhstan", Code= "KZ"},
            new CountryData {Name= "Kenya", Code= "KE"},
            new CountryData {Name= "Kiribati", Code= "KI"},
            new CountryData {Name= "Korea, Democratic People'S Republic of", Code= "KP"},
            new CountryData {Name= "Korea, Republic of", Code= "KR"},
            new CountryData {Name= "Kuwait", Code= "KW"},
            new CountryData {Name= "Kyrgyzstan", Code= "KG"},
            new CountryData {Name= "Lao People'S Democratic Republic", Code= "LA"},
            new CountryData {Name= "Latvia", Code= "LV"},
            new CountryData {Name= "Lebanon", Code= "LB"},
            new CountryData {Name= "Lesotho", Code= "LS"},
            new CountryData {Name= "Liberia", Code= "LR"},
            new CountryData {Name= "Libyan Arab Jamahiriya", Code= "LY"},
            new CountryData {Name= "Liechtenstein", Code= "LI"},
            new CountryData {Name= "Lithuania", Code= "LT"},
            new CountryData {Name= "Luxembourg", Code= "LU"},
            new CountryData {Name= "Macao", Code= "MO"},
            new CountryData {Name= "Macedonia, The Former Yugoslav Republic of", Code= "MK"},
            new CountryData {Name= "Madagascar", Code= "MG"},
            new CountryData {Name= "Malawi", Code= "MW"},
            new CountryData {Name= "Malaysia", Code= "MY"},
            new CountryData {Name= "Maldives", Code= "MV"},
            new CountryData {Name= "Mali", Code= "ML"},
            new CountryData {Name= "Malta", Code= "MT"},
            new CountryData {Name= "Marshall Islands", Code= "MH"},
            new CountryData {Name= "Martinique", Code= "MQ"},
            new CountryData {Name= "Mauritania", Code= "MR"},
            new CountryData {Name= "Mauritius", Code= "MU"},
            new CountryData {Name= "Mayotte", Code= "YT"},
            new CountryData {Name= "Mexico", Code= "MX"},
            new CountryData {Name= "Micronesia, Federated States of", Code= "FM"},
            new CountryData {Name= "Moldova, Republic of", Code= "MD"},
            new CountryData {Name= "Monaco", Code= "MC"},
            new CountryData {Name= "Mongolia", Code= "MN"},
            new CountryData {Name= "Montenegro", Code= "ME"},
            new CountryData {Name= "Montserrat", Code= "MS"},
            new CountryData {Name= "Morocco", Code= "MA"},
            new CountryData {Name= "Mozambique", Code= "MZ"},
            new CountryData {Name= "Myanmar", Code= "MM"},
            new CountryData {Name= "Namibia", Code= "NA"},
            new CountryData {Name= "Nauru", Code= "NR"},
            new CountryData {Name= "Nepal", Code= "NP"},
            new CountryData {Name= "Netherlands", Code= "NL"},
            new CountryData {Name= "Netherlands Antilles", Code= "AN"},
            new CountryData {Name= "new CountryData Caledonia", Code= "NC"},
            new CountryData {Name= "new CountryData Zealand", Code= "NZ"},
            new CountryData {Name= "Nicaragua", Code= "NI"},
            new CountryData {Name= "Niger", Code= "NE"},
            new CountryData {Name= "Nigeria", Code= "NG"},
            new CountryData {Name= "Niue", Code= "NU"},
            new CountryData {Name= "Norfolk Island", Code= "NF"},
            new CountryData {Name= "Northern Mariana Islands", Code= "MP"},
            new CountryData {Name= "Norway", Code= "NO"},
            new CountryData {Name= "Oman", Code= "OM"},
            new CountryData {Name= "Pakistan", Code= "PK"},
            new CountryData {Name= "Palau", Code= "PW"},
            new CountryData {Name= "Palestinian Territory, Occupied", Code= "PS"},
            new CountryData {Name= "Panama", Code= "PA"},
            new CountryData {Name= "Papua new CountryData Guinea", Code= "PG"},
            new CountryData {Name= "Paraguay", Code= "PY"},
            new CountryData {Name= "Peru", Code= "PE"},
            new CountryData {Name= "Philippines", Code= "PH"},
            new CountryData {Name= "Pitcairn", Code= "PN"},
            new CountryData {Name= "Poland", Code= "PL"},
            new CountryData {Name= "Portugal", Code= "PT"},
            new CountryData {Name= "Puerto Rico", Code= "PR"},
            new CountryData {Name= "Qatar", Code= "QA"},
            new CountryData {Name= "Reunion", Code= "RE"},
            new CountryData {Name= "Romania", Code= "RO"},
            new CountryData {Name= "Russian Federation", Code= "RU"},
            new CountryData {Name= "RWANDA", Code= "RW"},
            new CountryData {Name= "Saint Helena", Code= "SH"},
            new CountryData {Name= "Saint Kitts and Nevis", Code= "KN"},
            new CountryData {Name= "Saint Lucia", Code= "LC"},
            new CountryData {Name= "Saint Pierre and Miquelon", Code= "PM"},
            new CountryData {Name= "Saint Vincent and the Grenadines", Code= "VC"},
            new CountryData {Name= "Samoa", Code= "WS"},
            new CountryData {Name= "San Marino", Code= "SM"},
            new CountryData {Name= "Sao Tome and Principe", Code= "ST"},
            new CountryData {Name= "Saudi Arabia", Code= "SA"},
            new CountryData {Name= "Senegal", Code= "SN"},
            new CountryData {Name= "Serbia", Code= "RS"},
            new CountryData {Name= "Seychelles", Code= "SC"},
            new CountryData {Name= "Sierra Leone", Code= "SL"},
            new CountryData {Name= "Singapore", Code= "SG"},
            new CountryData {Name= "Slovakia", Code= "SK"},
            new CountryData {Name= "Slovenia", Code= "SI"},
            new CountryData {Name= "Solomon Islands", Code= "SB"},
            new CountryData {Name= "Somalia", Code= "SO"},
            new CountryData {Name= "South Africa", Code= "ZA"},
            new CountryData {Name= "South Georgia and the South Sandwich Islands", Code= "GS"},
            new CountryData {Name= "Spain", Code= "ES"},
            new CountryData {Name= "Sri Lanka", Code= "LK"},
            new CountryData {Name= "Sudan", Code= "SD"},
            new CountryData {Name= "Suriname", Code= "SR"},
            new CountryData {Name= "Svalbard and Jan Mayen", Code= "SJ"},
            new CountryData {Name= "Swaziland", Code= "SZ"},
            new CountryData {Name= "Sweden", Code= "SE"},
            new CountryData {Name= "Switzerland", Code= "CH"},
            new CountryData {Name= "Syrian Arab Republic", Code= "SY"},
            new CountryData {Name= "Taiwan, Province of China", Code= "TW"},
            new CountryData {Name= "Tajikistan", Code= "TJ"},
            new CountryData {Name= "Tanzania, United Republic of", Code= "TZ"},
            new CountryData {Name= "Thailand", Code= "TH"},
            new CountryData {Name= "Timor-Leste", Code= "TL"},
            new CountryData {Name= "Togo", Code= "TG"},
            new CountryData {Name= "Tokelau", Code= "TK"},
            new CountryData {Name= "Tonga", Code= "TO"},
            new CountryData {Name= "Trinidad and Tobago", Code= "TT"},
            new CountryData {Name= "Tunisia", Code= "TN"},
            new CountryData {Name= "Turkey", Code= "TR"},
            new CountryData {Name= "Turkmenistan", Code= "TM"},
            new CountryData {Name= "Turks and Caicos Islands", Code= "TC"},
            new CountryData {Name= "Tuvalu", Code= "TV"},
            new CountryData {Name= "Uganda", Code= "UG"},
            new CountryData {Name= "Ukraine", Code= "UA"},
            new CountryData {Name= "United Arab Emirates", Code= "AE"},
            new CountryData {Name= "United Kingdom", Code= "GB"},
            new CountryData {Name= "United States", Code= "US"},
            new CountryData {Name= "United States Minor Outlying Islands", Code= "UM"},
            new CountryData {Name= "Uruguay", Code= "UY"},
            new CountryData {Name= "Uzbekistan", Code= "UZ"},
            new CountryData {Name= "Vanuatu", Code= "VU"},
            new CountryData {Name= "Venezuela", Code= "VE"},
            new CountryData {Name= "Viet Nam", Code= "VN"},
            new CountryData {Name= "Virgin Islands, British", Code= "VG"},
            new CountryData {Name= "Virgin Islands, U.S.", Code= "VI"},
            new CountryData {Name= "Wallis and Futuna", Code= "WF"},
            new CountryData {Name= "Western Sahara", Code= "EH"},
            new CountryData {Name= "Yemen", Code= "YE"},
            new CountryData {Name= "Zambia", Code= "ZM"},
            new CountryData {Name= "Zimbabwe", Code= "ZW"}
            };

        public static IEnumerable<CountryData> GetCountries()
        {
            return countries;
        }

        public static CountryData GetCountryByCode(string code)
        {
            return countries.SingleOrDefault(s => s.Code == code);
        }


    }

}
